apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven-demo-dep
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: maven-demo
    spec:
      imagePullSecrets:            # 加入harbor-secret
        - name: harbor-secret
      containers:
        - name: maven-demo-pod
          image: harbor.asoco.com.cn/dse/maven-demo:TAG
          ports:
            - containerPort: 8080
