image: docker:18.06.1

variables:
  CON_NAME: "smart-factory-transfar"
  CON_PORT: 8089
  HOST_PORT: 8089
  HAR_NAME: dse
  HAR_PASSWD: Dse.123456


stages:
  - build
  - restart

build:
  image: maven:alpine
  stage: build
  script:
    - cd bootdo/ && mvn clean package
    - ls -l *
  artifacts:
    name: ${CON_NAME}-$(date +%Y%m%d)-${CI_JOB_ID}
    expire_in: 1 day
    paths:
      - bootdo/target/*.jar
  only:
    - master

restart:
  stage: restart
  script:
#   - if [ $(docker ps -aq --filter name=^${CON_NAME}$) ];then docker diff ${CON_NAME};fi
    - docker build -t harbor.asoco.com.cn/dse/${CON_NAME}:latest .
    - if [ $(docker ps -aq --filter name=^/${CON_NAME}$) ]; then docker stop ${CON_NAME} && docker rm ${CON_NAME};fi
    - docker run -d --name ${CON_NAME} -e TZ="Asia/Shanghai" -v /etc/localtime:/etc/localtime:ro -p ${HOST_PORT}:${CON_PORT} harbor.asoco.com.cn/dse/${CON_NAME}:latest
    - docker login -u ${HAR_NAME} -p ${HAR_PASSWD} harbor.asoco.com.cn
    - docker push harbor.asoco.com.cn/dse/${CON_NAME}:latest
 only:
    - master                            
