image: docker:18.06.1

variables:
  CON_NAME: "smart-factory-transfar"
  CON_PORT: 8089
  HOST_PORT: 8089
  HAR_NAME: dse
  HAR_PASSWD: Dse.123456


stages:
  - build
  - restart
  - zabbix

build:
  image: maven:alpine
  stage: build
  script:
    - cd bootdo/ && mvn clean package
    - ls -l *
  artifacts:
    name: ${CON_NAME}-$(date +%Y%m%d)-${CI_JOB_ID}
    expire_in: 1 day
    paths:
      - bootdo/target/*.jar
  only:
    - master

restart:
  stage: restart
  script:
#   - if [ $(docker ps -aq --filter name=^${CON_NAME}$) ];then docker diff ${CON_NAME};fi
    - docker build -t harbor.asoco.com.cn/dse/${CON_NAME}:latest .
    - if [ $(docker ps -aq --filter name=^/${CON_NAME}$) ]; then docker stop ${CON_NAME} && docker rm ${CON_NAME};fi
    - docker run -d --name ${CON_NAME} -e TZ="Asia/Shanghai" -v /etc/localtime:/etc/localtime:ro -p ${HOST_PORT}:${CON_PORT} harbor.asoco.com.cn/dse/${CON_NAME}:latest
    - docker login -u ${HAR_NAME} -p ${HAR_PASSWD} harbor.asoco.com.cn
    - docker push harbor.asoco.com.cn/dse/${CON_NAME}:latest
 only:
    - master                            

zabbix:
  stage: failed
  before_script:
    - which ssh-agent || sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_99" | tr -d '\r'| ssh-add
    - ssh-add -l
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - /bin/zabbix_sender -z 192.168.1.82 -p 10051 -s dseci.example.com -k gitlab-ci -o "- 项目：$CI_PROJECT_NAME\n- 分支：$CI_COMMIT_REF_NAME\n- 提交人：$GITLAB_USER_NAME\n- URL:$CI_PROJECT_URL/pipelines"
  when: on_failure
