stages:
  - build-dev
  - build-prod
  - sonar


build-dev:
  stage: build-dev
  script:
    - mvn package -Pdev
  after_script:
    - unzip -oq target/ia-lng2.jar 
    - mkdir config
    - mv *.properties module_lng2_dbg.xml config/
    - sed -i 's/Class-Path:\ /Class-Path:\ config\/\ /' META-INF/MANIFEST.MF
    - jar -cfM0 ia-lng2-dgb.jar com/ META-INF/ profiles/
    - rm -fr ./lib;mv target/lib .
  artifacts:
    name: ia-lng2-dev$(date +%Y%m%d)
    paths:
      - ia-lng2-dgb.jar
      - config/
      - lib/
  only:
    - master
    
build-prod:
  stage: build-prod
  script:
    - mvn package -Pprod
  after_script:
    - unzip -oq target/ia-lng2.jar 
    - mkdir config
    - mv *.properties module_lng2_dbg.xml config/
    - sed -i 's/Class-Path:\ /Class-Path:\ config\/\ /' META-INF/MANIFEST.MF
    - jar -cfM0 ia-lng2-dgb.jar com/ META-INF/ profiles/
    - rm -fr ./lib;mv target/lib .
  artifacts:
    name: ia-lng2-prod$(date +%Y%m%d)
    paths:
      - ia-lng2-dgb.jar
      - config/
      - lib/
  only:
    - master

sonar:
  stage: sonar
  script:
    - mvn sonar:sonar -Dsonar.java.binaries=src
  allow_failure: true
  only:
    - master

